## Colors configuration
[colors.primary]
background = "#04071B"
foreground = "#aec1d6"

[colors.normal]
black   = "#04071B"
red     = "#282492"
green   = "#4F2E9E"
yellow  = "#7733BB"
blue    = "#56669B"
magenta = "#7041B8"
cyan    = "#8B56D0"
white   = "#aec1d6"

[colors.bright]
black   = "#798795"
red     = "#282492"
green   = "#4F2E9E"
yellow  = "#7733BB"
blue    = "#56669B"
magenta = "#7041B8"
cyan    = "#8B56D0"
white   = "#aec1d6"
